# -*- coding: utf-8 -*-
"""audio_augmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O6cwIJTIt_eu-Y9VH22bKwDzBHU_daRA
"""

import pandas as pd
import numpy as np
import librosa

def add_whitenoise(sig):
  wn = np.random.randn(len(sig))
  wn_1000=wn/1000*np.random.randint(1,6)
  sig_wn = sig + wn_1000
  return sig_wn
  
def shift_audio(sig, shift):
  sig_roll = np.roll(sig, shift)
  return sig_roll

def stratch_audio(sig, rate=1):
  input_length = len(sig)
  sig = librosa.effects.time_stretch(sig, rate)
  if len(sig)>input_length:
      sig = sig[:input_length]
  else:
      sig = np.pad(sig, (0, max(0, input_length - len(sig))), "constant")
  return sig

